---
- name: user root
  copy: src=/vagrant/files/dot/.bashrc dest=/root/.bashrc owner=root group=root

- name: user vagrant
  copy: src=/vagrant/files/dot/.bashrc dest=/home/vagrant/.bashrc owner=vagrant group=vagrant
  when: inventory_hostname == "localhost"