- name: include apps
  include_vars: "apps.yml"

- name: add nginx configuration
  template: src={{ item.framework }}.conf.j2 dest=/etc/nginx/conf.d/{{ item.name }}.conf mode=0640
  with_items: apps

#- name: install app from git repo
#  command: git clone {{ item.repository }} /var/www/{{ item.name }}
#  with_items: apps
#
#- name: install app from git repo
#  command: git checkout {{ item.version }}
#  with_items: apps
