- name: install mysql-server
  apt: pkg=mysql-server state=installed

- name: install mysql-client
  apt: pkg=mysql-client state=installed

- name: install python-mysqldb
  apt: pkg=python-mysqldb  state=installed

- name: Start the MySQL service
  action: service name=mysql state=started

- name: update mysql root password for all root accounts
  mysql_user: name=root host={{ item }} password={{ mysql_root_password }}
  with_items:
    - "{{ ansible_hostname }}"
    - "{{ ansible_eth0.ipv4.address }}"
    - 127.0.0.1
    - ::1
    - localhost

- name: copy .my.cnf file with root password credentials
  template: src=my.cnf.j2 dest=/root/.my.cnf owner=root mode=0600

- name: delete anonymous MySQL server user
  action: mysql_user user="" state="absent"

- name: remove the MySQL test database
  action: mysql_db db=test state=absent