---
- name: Webserver
  hosts: webserver
  remote_user: deploy
  sudo: yes
  vars_files:
    - [ '../config/config.yml' ]

  roles:
    - common
    - nginx
    - mysql
    - php
    - apps
    - {role: dev, when: inventory_hostname == "localhost"}
    - {role: samba, when: inventory_hostname == "localhost"}