---
- name: Webserver
  hosts: webserver
  remote_user: deploy
  sudo: yes
  vars_files:
    - [ '../config/config.yml' ]
  vars:
    - deploy_timestamp: "{{ ansible_date_time.year }}{{ ansible_date_time.month }}{{ ansible_date_time.day }}{{ ansible_date_time.hour }}{{ ansible_date_time.second }}"

  roles:
    - common
    - nginx
    - mysql
    - php
    - {role: samba, when: inventory_hostname == "localhost"}