---
- name: Webserver
  hosts: webserver
  remote_user: deploy
  sudo: yes
  vars_files:
    - "../config/config.yml"

  roles:
    - common
    - password
    - nginx
    - mysql
    - php
    - nodejs
    - bower
    - grunt
    - {role: capifony, when: inventory_hostname == "localhost"}
    - {role: sqlite, when: inventory_hostname == "localhost"}
    - {role: samba, when: inventory_hostname == "localhost"}
    - {role: adminer, when: inventory_hostname == "localhost"}