---
- name: Configure webserver
  hosts: webservers
  remote_user: deploy
  sudo: yes

  roles:
    - common
    - security
    - nginx
    - mysql
    - php
    - apps
    - {role: dev, when: inventory_hostname == "localhost"}
    - {role: samba, when: inventory_hostname == "localhost"}